# Generated by Django 5.0.1 on 2024-05-18 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0002_alter_review_rating'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ReservationMeal',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('date', models.DateField()),
        #         ('time', models.TimeField()),
        #         ('people', models.CharField(max_length=50)),
        #         ('table', models.CharField(max_length=50)),
        #         ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsova.meal')),
        #         ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsova.reservation_main')),
        #     ],
        # ),
    ]
