# Generated by Django 5.0.1 on 2024-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0002_alter_review_rating'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='reservationmeal',
    #         name='table2',
    #         field=models.CharField(default=1, max_length=50),
    #         preserve_default=False,
    #     ),
    # ]
