# Generated by Django 5.0.1 on 2024-05-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0003_reservationmeal'),
    ]

    # operations = [
    #     migrations.AlterModelTable(
    #         name='reservationmeal',
    #         table='ReservationMeal',
    #     ),
    # ]
