# Generated by Django 5.0.1 on 2024-05-18 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0003_reservationmeal'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Reservation_Meal',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('meal_name', models.CharField(max_length=100)),
    #             ('date', models.DateField()),
    #             ('time', models.TimeField()),
    #             ('people', models.CharField(max_length=50)),
    #             ('table', models.CharField(max_length=50)),
    #             ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsova.meal')),
    #             ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsova.reservation_main')),
    #         ],
    #         options={
    #             'db_table': 'Reservation_Meal',
    #         },
    #     ),
    # ]
