# Generated by Django 5.0.1 on 2024-05-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0004_alter_reservationmeal_table'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='reservationmeal',
    #         name='meal_name',
    #         field=models.CharField(default=1, max_length=100),
    #         preserve_default=False,
    #     ),
    # ]
