# Generated by Django 5.0.1 on 2024-05-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0006_reservationmeal_table2'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='reservationmeal',
    #         name='table2',
    #     ),
    # ]
