# Generated by Django 5.0.1 on 2024-05-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0003_reservationmeal_table2'),
        ('kyrsova', '0005_alter_reservationmeal_table'),
        ('kyrsova', '0007_remove_reservationmeal_table2'),
    ]

    operations = [
    ]
