# Generated by Django 5.0.1 on 2024-05-18 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0008_merge_20240518_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('people', models.CharField(max_length=50)),
                ('table', models.CharField(max_length=50)),
                ('table2', models.CharField(max_length=50)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsova.meal')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsova.reservation_main')),
            ],
            options={
                'db_table': 'Reservation_Meal',
            },
        ),
    ]
