# Generated by Django 5.0.1 on 2024-05-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0009_reservationmeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmeal',
            name='table2',
        ),
    ]
