# Generated by Django 5.0.1 on 2024-05-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0010_remove_reservationmeal_table2'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmeal',
            name='meal_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservationmeal',
            name='meal_name',
            field=models.CharField(max_length=150),
        ),
    ]
