# Generated by Django 5.0.1 on 2024-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsova', '0011_reservationmeal_meal_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmeal',
            name='meal_category',
        ),
        migrations.AlterField(
            model_name='reservationmeal',
            name='meal_name',
            field=models.CharField(max_length=100),
        ),
    ]
